#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe omp 8

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

zcat /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz | grep "bc1=" | awk '{print $2,$3}' | sed s/bc1=// | sed s/bc2=// | sed s/" "// | sort | uniq -c >combined_counts

echo "Job finished: $(date +%F)"
